### ISSUE TITLE
Compatibility with nptyping

### ISSUE THREAD

**Issue by hallmeier** [ramonhagenaars/typish#11]
Awesome that `np.ndarray`s now work!

Could you also make `instance_of` compatible with `nptyping.NDArray`? These work only with `isinstance` so far, so both fail in this case:

```
import numpy as np
from typing import List, Union, Any
from nptyping import NDArray
from typish import instance_of

instance_of([[1, 2], np.array([3, 4])], List[Union[List[int], NDArray[Any, int]]])
isinstance([[1, 2], np.array([3, 4])], List[Union[List[int], NDArray[Any, int]]])
```

**Comment by ramonhagenaars** [comment]
Hi @hallmeier. Great to hear that you like my projects. 😃 
I'm working on a typish release that supports `nptyping.NDArray`. I'll be available soon.
