### ISSUE TITLE
Releases and tags

### ISSUE THREAD

**Issue by jaimergp** [ramonhagenaars/typish#16]
Conda Forge requires all dependencies of a package to be present on Conda Forge too. Since this is a dependency of `nptyping`, I have to submit a recipe for this one.

However, the release workflow for `typish` is not entirely clear. Although there are named branches with `Release/*`, there are no proper releases and for example there's no branch for the current PyPI release (1.6.0).

I guess for now we'd need at least a tag for the corresponding commit that created `1.6.0`. For the future, using tags and releases might help in deploying the packages to conda forge (since this will be used by the bots to autosubmit the updated PRs for new versions, among other cool features).

**Comment by ramonhagenaars** [comment]
You're right about that @jaimergp, I've let myself go a bit on this project when it comes to release management. 😄 I'm preparing a `1.7.0` release, I'll start supplying proper releases from that version onward.

**Comment by jaimergp** [comment]
Thank you!
