### ISSUE TITLE
"setup.py" accidentally installs tests

### ISSUE THREAD

**Issue by leycec** [ramonhagenaars/typish#28]
Greetings, [horrifying mountain gorilla known as Ramon that will hopefully not eat my face off](https://github.com/ramonhagenaars). I'm currently packaging both `nptyping` and `typish` for Gentoo Linux – pursuant to eventually packaging [CadQuery](https://cadquery.readthedocs.io/en/latest), which requires `nptyping` and thus `typish`.

Everything mostly went well. No dependencies, for example: *"Can't complain about that."* I couldn't help but notice, however, that `setup.py` for both `nptyping` *and* `typish` accidentally installs the ambiguously named `tests` and `test_resources` packages bundled with `nptyping` and `typish`:

```
    # This line...
    packages=find_packages(exclude=('tests', 'test_resources')),

    # ...should really look like this instead.
    packages=find_packages(exclude=('tests', 'tests.*', 'test_resources', 'test_resources.*')),
```

Hopefully, that's unintentional. The surprisingly fragile `exclude` key to the `setuptools.find_packages()` function doesn't behave as expected, because `setuptools` is insane. Since installing packages with ambiguous names like that is sensibly prohibited on Gentoo, we're patching your `setup.py` with an admittedly disgusting `sed` one-liner. An official fix would make us less squeamish.

Thanks for all the duck-typing! The world needs more type hints. :duck:

**Comment by ramonhagenaars** [comment]
Greetings to you, bear loving stranger! Don't worry about me eating your face off: I gave up on such behavior some time ago and adopted the vegetarian lifestyle like most of [my relatives](https://www.worldwildlife.org/stories/what-do-gorillas-eat-and-other-gorilla-facts).

I must reluctantly admit that this has been flawed from the very beginning of this package. 😬 

Thank you for pointing this out! Expect a patch soon!

**Comment by leycec** [comment]
> Don't worry about me eating your face off:

Sweeter words have never been spoken.

> I gave up on such behavior some time ago...

**...wait a minute.** By "some time ago," how long ago *exactly* are we talking? Five minutes? Five days? Five years? I don't like to sweat the fine details, but I'm kinda concerned about a relapse over here.

> ...and adopted the vegetarian lifestyle like most of my relatives.

"Most": also a concerning qualifier in this context.

Seriously, though. Thanks for the heads up on mountain gorilla diet! I try not to think about them, because I volunteered in Africa in my youth. Their ongoing struggle for mere existence calls up sepia-tinged memories I'd rather keep repressing.

You are doing the good work here. Faces in the mist approve. :gorilla:

**Comment by ramonhagenaars** [comment]
Love your posts, they make me smile. 😄
